#### Tensor 이해 - 생성
- Tensor란?
    * pythorch에서 데이터를 저장하는 객체
    * 모델에 입력/출력 데이터 형태
- 개발 버전 : torch v.2.4.1

In [4]:
import torch
print(f'torch.v  {torch.__version__}')

torch.v  2.4.1


In [13]:
# ----------------------------------------------------------
# 함수기능 : 텐서 속성 정보 출력 함수
# ----------------------------------------------------------
def printInfo(obj,obj_name):
    print(f'\n{obj_name}')
    print(f'shape : {obj.shape}')
    print(f'ndim  : {obj.ndim}차원')
    print(f'dtype : {obj.dtype}')
    print(f'device : {obj.device}')
    print(f'data : \n{obj.data}')

- 텐서생성 [1]torch.tensor()

In [14]:
## 데이터 1개 즉, 스칼라
dataTF=torch.tensor(10)  #메모리 8칸 사용
printInfo(dataTF, 'dataTF')

dataTF=torch.tensor(10, dtype=torch.uint8) # 메모리 1칸 사용
printInfo(dataTF, 'dataTF')


dataTF
shape : torch.Size([])
ndim  : 0차원
dtype : torch.int64
device : cpu
data : 
10

dataTF
shape : torch.Size([])
ndim  : 0차원
dtype : torch.uint8
device : cpu
data : 
10


In [15]:
# ----------------------------------------------------
# 생성 형식 : torch.tensor(데이터)
# ----------------------------------------------------
ten1 = torch.tensor(10)
ten2 = torch.tensor([22,33,44])
ten3 = torch.tensor([[90,91],[80,81], [70,71]])
# 텐서 정보 출력
printInfo(ten1, 'ten1')
printInfo(ten2, 'ten2')
printInfo(ten3, 'ten3')


ten1
shape : torch.Size([])
ndim  : 0차원
dtype : torch.int64
device : cpu
data : 
10

ten2
shape : torch.Size([3])
ndim  : 1차원
dtype : torch.int64
device : cpu
data : 
tensor([22, 33, 44])

ten3
shape : torch.Size([3, 2])
ndim  : 2차원
dtype : torch.int64
device : cpu
data : 
tensor([[90, 91],
        [80, 81],
        [70, 71]])


In [16]:
## 데이터 1개 즉, 벡터 1D
dataTF=torch.tensor([10])  #메모리 8칸 사용
printInfo(dataTF, 'dataTF')

dataTF=torch.tensor([10], dtype=torch.uint8) # 메모리 1칸 사용
printInfo(dataTF, 'dataTF')


dataTF
shape : torch.Size([1])
ndim  : 1차원
dtype : torch.int64
device : cpu
data : 
tensor([10])

dataTF
shape : torch.Size([1])
ndim  : 1차원
dtype : torch.uint8
device : cpu
data : 
tensor([10], dtype=torch.uint8)


In [17]:
## 데이터 1개 즉, 행렬 2D
dataTF=torch.tensor([[10]])  #메모리 8칸 사용
printInfo(dataTF, 'dataTF')

dataTF=torch.tensor([[10]], dtype=torch.uint8) # 메모리 1칸 사용
printInfo(dataTF, 'dataTF')


dataTF
shape : torch.Size([1, 1])
ndim  : 2차원
dtype : torch.int64
device : cpu
data : 
tensor([[10]])

dataTF
shape : torch.Size([1, 1])
ndim  : 2차원
dtype : torch.uint8
device : cpu
data : 
tensor([[10]], dtype=torch.uint8)


In [21]:
# ----------------------------------------------------
# 0으로 채운 텐서 생성 : torch.zeros( 행 [, 열 ] )
# ----------------------------------------------------
zten1=torch.zeros(2,5)
zten2=torch.zeros(3)
printInfo(zten1, 'zten1')
printInfo(zten2, 'zten2')


zten1
shape : torch.Size([2, 5])
ndim  : 2차원
dtype : torch.float32
device : cpu
data : 
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

zten2
shape : torch.Size([3])
ndim  : 1차원
dtype : torch.float32
device : cpu
data : 
tensor([0., 0., 0.])


In [22]:
# ------------------------------------------------------------
# 모든 값 특정 값으로 채운 텐서 생성 : torch.full( (행, 열 ), 데이터 )
# -------------------------------------------------------------
ften1=torch.full((3, ), 10)
ften2=torch.full((3,2), 10)
printInfo(ften1, 'ften1')
printInfo(ften2, 'ften2')


ften1
shape : torch.Size([3])
ndim  : 1차원
dtype : torch.int64
device : cpu
data : 
tensor([10, 10, 10])

ften2
shape : torch.Size([3, 2])
ndim  : 2차원
dtype : torch.int64
device : cpu
data : 
tensor([[10, 10],
        [10, 10],
        [10, 10]])


In [23]:
# ----------------------------------------------------
# 모든 값을 1로 채운 텐서 생성 : torch.ones( 행 [, 열 ] )
# ----------------------------------------------------
oten1=torch.ones(2,3)
oten2=torch.ones(3)
printInfo(oten1, 'oten1')
printInfo(oten2, 'oten2')


oten1
shape : torch.Size([2, 3])
ndim  : 2차원
dtype : torch.float32
device : cpu
data : 
tensor([[1., 1., 1.],
        [1., 1., 1.]])

oten2
shape : torch.Size([3])
ndim  : 1차원
dtype : torch.float32
device : cpu
data : 
tensor([1., 1., 1.])


In [19]:
# ------------------------------------------------------------
# 대각선을 1로 채운 텐서 생성 : torch.eye( (행 [, 열 ])
# -------------------------------------------------------------
eten1=torch.eye(3)
eten2=torch.eye(3,5)
printInfo(eten1, 'eten1')
printInfo(eten2, 'eten2')


eten1
shape : torch.Size([3, 3])
ndim  : 2차원
dtype : torch.float32
device : cpu
data : 
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

eten2
shape : torch.Size([3, 5])
ndim  : 2차원
dtype : torch.float32
device : cpu
data : 
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.]])


In [24]:
## 임의의 랜덤 값으로 채운 텐서 생성 => torch.rand()
# ----------------------------------------------------
# - 값의 범위 : 0<= ~ <1 [0, 1) torch.rand(행, 열)
# ----------------------------------------------------
torch.manual_seed(1)
rten1=torch.rand(2,3)
printInfo(rten1, 'rten1')


rten1
shape : torch.Size([2, 3])
ndim  : 2차원
dtype : torch.float32
device : cpu
data : 
tensor([[0.7576, 0.2793, 0.4031],
        [0.7347, 0.0293, 0.7999]])
