#### TENSOR 변환

In [1]:
## 모듈 로딩
import torch

- Python 객체 ==> Tensor 변환

In [2]:
## List ==> Tensor
data = list(range(1,10))

In [6]:
##torch.as_tensor()
dataTS=torch.as_tensor(data,dtype=torch.int8)
dataTS, dataTS.shape, dataTS.ndim, dataTS.dtype

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int8),
 torch.Size([9]),
 1,
 torch.int8)

In [14]:
data[0]=100

In [15]:
data, dataTS # data는python객체, 바뀜, dataTS는 안바뀜

([100, 2, 3, 4, 5, 6, 7, 8, 9],
 tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int8))

- Numpy, ndarry변환 ==> Tensor 변환

In [7]:
import numpy as np

In [8]:
arr1=np.array([1,2,3])
arr1, arr1.dtype, arr1.ndim

(array([1, 2, 3]), dtype('int32'), 1)

In [16]:
arr1=np.array([1,2,3])
arr1, arr1.dtype, arr1.ndim

(array([1, 2, 3]), dtype('int32'), 1)

In [17]:
arrTS=torch.as_tensor(arr1, dtype=torch.float32)
arrTS

# as_tensor: converts data in to 
# t[0]을 바꿧는데 array도 바뀌는 건 view형식 

tensor([1., 2., 3.])

In [10]:
arr1[0]=77

In [18]:
arr1, arrTS

(array([1, 2, 3]), tensor([1., 2., 3.]))

In [19]:
arrTS[0]=99

In [20]:
arr1, arrTS
# 이미 있다면 그것을 주고 없으면 copy를 준다
# view 나 copy나 둘중하나 준다

(array([1, 2, 3]), tensor([99.,  2.,  3.]))

- Numpy ndarray ==> Tensor 변환 : from_numpy()

In [22]:
arr1=np.array([5,7,9], dtype=np.float32)
print(arr1)

arr1, arr1.data, arr1.size, arr1.itemsize  # size ( 요소갯수)* itemsize(요소당 바이트 크기) ==> 12바이트
# 메모리 주소: arr1.data

print(f'데이터 저장 메모리 주소  : {arr1.data}')
print(f'원소/요소 갯수          : {arr1.size}')
print(f'원소/요소 1개 크기      : {arr1.itemsize}')
print(f'타입                   : {arr1.dtype}')
print(f'방향                   : {arr1.strides}')

[5. 7. 9.]
데이터 저장 메모리 주소  : <memory at 0x0000018EA77E3640>
원소/요소 갯수          : 3
원소/요소 1개 크기      : 4
타입                   : float32
방향                   : (4,)


In [23]:
arrTS=torch.from_numpy(arr1)
arrTS

tensor([5., 7., 9.])