#### Tensor 이해

In [1]:
### 모듈로딩
import torch

- 타입지정 Tensor 클래스 활용
    * 데이터 타입을 설정 후 생성
    * 데이터 사이즈 설정한 텐서 생성 시 사용
    * 데이터의 자료형 변환한 텐서 생성 시 사용

In [2]:
### 정수형 텐서 생성
data=[1.4,2.8,3.1]

In [4]:
### 1바이트 정수형 텐서 생성
dataTS1=torch.CharTensor(data)
dataTS11=torch.tensor(data,dtype=torch.int8)

print(dataTS1, dataTS11, sep='\n')

tensor([1, 2, 3], dtype=torch.int8)
tensor([1, 2, 3], dtype=torch.int8)


C:\Users\KDP-27\AppData\Local\Temp\ipykernel_11588\4057317039.py:2: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  dataTS1=torch.CharTensor(data)
C:\Users\KDP-27\AppData\Local\Temp\ipykernel_11588\4057317039.py:3: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  dataTS11=torch.tensor(data,dtype=torch.int8)


In [5]:
### 2바이트 정수형 텐서 생성
dataTS1=torch.CharTensor(data)
dataTS11=torch.tensor(data,dtype=torch.int16)

print(dataTS1, dataTS11, sep='\n')

tensor([1, 2, 3], dtype=torch.int8)
tensor([1, 2, 3], dtype=torch.int16)


C:\Users\KDP-27\AppData\Local\Temp\ipykernel_11588\410226504.py:2: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  dataTS1=torch.CharTensor(data)
C:\Users\KDP-27\AppData\Local\Temp\ipykernel_11588\410226504.py:3: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  dataTS11=torch.tensor(data,dtype=torch.int16)


In [7]:
### 논리형 텐서 생성
dataTS1=torch.BoolTensor(data)
dataTS11=torch.tensor(data,dtype=torch.int16)


print(dataTS1, dataTS11, sep='\n')

tensor([True, True, True])
tensor([1, 2, 3], dtype=torch.int16)


C:\Users\KDP-27\AppData\Local\Temp\ipykernel_11588\3866555197.py:3: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  dataTS11=torch.tensor(data,dtype=torch.int16)
