### Tensor 저장 구조 이해
- storage 객체
    * 텐서 객체의 메모리 저장 관련 정보 저장
    * offset : 첫 번째 원소 인덱스
    * stride : 원소 이동 위한 정보 저장
        * 다음 행 이동하기 위한 메모리 칸 수
        * 다음 열 이동하기 위한 메모리 칸 수

In [1]:
### 모듈로딩
import torch

In [5]:
dataTS=torch.tensor([[11,22,33],[44,55,66]], dtype=torch.int8)
print(dataTS,dataTS.stride,dataTS.ndim, dataTS.dtype,'\n' , sep='\n')

tensor([[11, 22, 33],
        [44, 55, 66]], dtype=torch.int8)
<built-in method stride of Tensor object at 0x0000013209F66540>
2
torch.int8




In [6]:
### STORAGE 정보 => 메모리에 저장된 데이터 형태 1D
print(dataTS.storage())

 11
 22
 33
 44
 55
 66
[torch.storage.TypedStorage(dtype=torch.int8, device=cpu) of size 6]


In [19]:
dataTS=torch.tensor([[11,22,33],[44,55,66]], dtype=torch.int8)
print(dataTS,dataTS.stride,dataTS.ndim, dataTS.dtype,'\n', sep='\n')

### STORAGE 정보 => 메모리에 저장된 데이터 형태 1D
print(dataTS.untyped_storage(), dataTS.storage_offset())

tensor([[11, 22, 33],
        [44, 55, 66]], dtype=torch.int8)
<built-in method stride of Tensor object at 0x000001320A30A360>
2
torch.int8


 11
 22
 33
 44
 55
 66
[torch.storage.UntypedStorage(device=cpu) of size 6] 0


In [20]:
mem_storage=dataTS.untyped_storage()
mem_storage[0],mem_storage[-1]

(11, 66)

In [21]:
for idx in range(6,):
    print(f'[{idx}번째 원소] - {mem_storage[idx]} : {id(mem_storage[idx])}')

[0번째 원소] - 11 : 140725253319904
[1번째 원소] - 22 : 140725253320256
[2번째 원소] - 33 : 140725253320608
[3번째 원소] - 44 : 140725253320960
[4번째 원소] - 55 : 140725253321312
[5번째 원소] - 66 : 140725253321664


In [22]:
dataTS.data

tensor([[11, 22, 33],
        [44, 55, 66]], dtype=torch.int8)

In [23]:
dataTS.data[0]

tensor([11, 22, 33], dtype=torch.int8)

In [24]:
dataTS.data_ptr() #실제 데이터가 저장되어 있는 주소 값

6201119085312