### Tensor 이해 - 형변환

In [1]:
### 모듈로딩
import torch

-방법[1] type(torch.XXXX)

In [2]:
# tensor 생성
dataTS1=torch.tensor([1,3,5])
dataTS1, dataTS1.dtype

(tensor([1, 3, 5]), torch.int64)

In [3]:
#int64 -> float
dataTS11=dataTS1.type(torch.float32)
dataTS11,dataTS11.dtype

(tensor([1., 3., 5.]), torch.float32)

-방법[2] 타입명()

In [4]:
# int64->float
dataTS11=dataTS1.float()
dataTS11,dataTS11.dtype 

(tensor([1., 3., 5.]), torch.float32)

In [5]:
# int64->boll
dataTS1.bool()

tensor([True, True, True])

-방법[3] to(dtype=000,device=000)

In [6]:
#int64->int8
dataTS1.to(dtype=torch.int8)

tensor([1, 3, 5], dtype=torch.int8)

In [7]:
dataTS1.to(dtype=torch.int8,
           device='cuda' if torch.cuda.is_available() else 'cpu')

tensor([1, 3, 5], dtype=torch.int8)

In [8]:
dataTS1[0], dataTS1[-1]

(tensor(1), tensor(5))

In [9]:
dataTS1[0],dataTS1[-2:]

(tensor(1), tensor([3, 5]))