#### ndarray & tensor의 차원 축소 & 추가
- 모델에 입출력 시에 shape 설정을 위해서 필요함

In [1]:
## 모듈 로딩
import cv2
import numpy as np
import torch

In [2]:
## 임의의 데이터 생성
data = np.full((200,100),7) #2D
data.shape, data.ndim

((200, 100), 2)

- [차원 추가] <hr>
    - Numpy 경우: ndarray.reshape(), np.expand_dims(), np.newaxis
    - Pytorch 경우 : reshape(), unsqueeze()

In [3]:
## ----------------------------------------------------------------------------
## numpy 기반
## ----------------------------------------------------------------------------
## - 채널 차원을 추가하기 => 방법 1 ) ndarra.reshape()
data1=data.reshape((200,100,1))
data1.shape, data1.ndim

((200, 100, 1), 3)

In [4]:
data1 #[[[7] * 100 ]*200] *3

array([[[7],
        [7],
        [7],
        ...,
        [7],
        [7],
        [7]],

       [[7],
        [7],
        [7],
        ...,
        [7],
        [7],
        [7]],

       [[7],
        [7],
        [7],
        ...,
        [7],
        [7],
        [7]],

       ...,

       [[7],
        [7],
        [7],
        ...,
        [7],
        [7],
        [7]],

       [[7],
        [7],
        [7],
        ...,
        [7],
        [7],
        [7]],

       [[7],
        [7],
        [7],
        ...,
        [7],
        [7],
        [7]]])

In [5]:
## - 채널 차원을 추가하기 => 방법2) np.expand_dims() //original=>(200, 100)

data2=np.expand_dims(data, axis=2)
data2.shape, data2.ndim

((200, 100, 1), 3)

In [6]:
## - 채널 차원을 추가하기 => 방법2) np.expand_dims() //original=>(200, 100)

data2=np.expand_dims(data, axis=0)
data2.shape, data2.ndim

((1, 200, 100), 3)

In [7]:
## - 채널 차원을 추가하기 => 방법2) np.newaxis 함수아님
print(data.shape, data.ndim)

data3 = data[:, :, np.newaxis]
data3.shape, data3.ndim

(200, 100) 2


((200, 100, 1), 3)

In [8]:
data4= data[:, np.newaxis, :]
data4.shape, data4.ndim

((200, 1, 100), 3)

In [9]:
## ----------------------------------------------------------------------------
## Pytorch 기반
## ----------------------------------------------------------------------------
print(type(data), data.shape, data.ndim)

dataTS=torch.IntTensor(data)
dataTS.shape

<class 'numpy.ndarray'> (200, 100) 2


torch.Size([200, 100])

In [10]:
dataTS #[  [7*100]*200   ]

tensor([[7, 7, 7,  ..., 7, 7, 7],
        [7, 7, 7,  ..., 7, 7, 7],
        [7, 7, 7,  ..., 7, 7, 7],
        ...,
        [7, 7, 7,  ..., 7, 7, 7],
        [7, 7, 7,  ..., 7, 7, 7],
        [7, 7, 7,  ..., 7, 7, 7]], dtype=torch.int32)

In [11]:
## 채널 차원을 추가하기 => 방법 1)
dataTS1 = dataTS.reshape((200,100,1))
dataTS1.shape

torch.Size([200, 100, 1])

In [12]:
## - 채널 차원을 추가하기 => 방법 2) unsqueeze(dim=숫자)
dataTS2 = dataTS.unsqueeze(dim=0)
dataTS2.shape

torch.Size([1, 200, 100])

In [13]:
dataTS2

tensor([[[7, 7, 7,  ..., 7, 7, 7],
         [7, 7, 7,  ..., 7, 7, 7],
         [7, 7, 7,  ..., 7, 7, 7],
         ...,
         [7, 7, 7,  ..., 7, 7, 7],
         [7, 7, 7,  ..., 7, 7, 7],
         [7, 7, 7,  ..., 7, 7, 7]]], dtype=torch.int32)

In [14]:
dataTS2 = dataTS.unsqueeze(dim=2)
dataTS2.shape

torch.Size([200, 100, 1])

In [15]:
dataTS2

tensor([[[7],
         [7],
         [7],
         ...,
         [7],
         [7],
         [7]],

        [[7],
         [7],
         [7],
         ...,
         [7],
         [7],
         [7]],

        [[7],
         [7],
         [7],
         ...,
         [7],
         [7],
         [7]],

        ...,

        [[7],
         [7],
         [7],
         ...,
         [7],
         [7],
         [7]],

        [[7],
         [7],
         [7],
         ...,
         [7],
         [7],
         [7]],

        [[7],
         [7],
         [7],
         ...,
         [7],
         [7],
         [7]]], dtype=torch.int32)

- [shape 변경] <hr>
    - Numpy 경우: T속성, transpose()
    - Pytorch 경우 : T속성, transpose(), permute()

In [16]:
## - shape 변경 => 방법 1) 속성 T : 현재 axis를 역순으로 변경
print(dataTS2.shape)
dataTS3=dataTS2.unsqueeze(dim=3)
print(dataTS3.shape)

torch.Size([200, 100, 1])
torch.Size([200, 100, 1, 1])


In [17]:
print("2D => ", dataTS.T.shape)
print("3D => ", dataTS2.T.shape)
print("4D => ", dataTS3.T.shape)

2D =>  torch.Size([100, 200])
3D =>  torch.Size([1, 100, 200])
4D =>  torch.Size([1, 1, 100, 200])


C:\Users\KDP-27\AppData\Local\Temp\ipykernel_16404\1831031371.py:2: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\TensorShape.cpp:3701.)
  print("3D => ", dataTS2.T.shape)


In [18]:
## - shape 변경 => 방법 2)  transpose() : 2개의 축 원하는 축 위치로 변경
print(dataTS.shape)
print(dataTS2.shape)
print(dataTS3.shape)

torch.Size([200, 100])
torch.Size([200, 100, 1])
torch.Size([200, 100, 1, 1])


In [19]:
print(dataTS2.transpose(1,2).shape) # [1] 이었던 100이 [2]였던 1이 1자리로 # 2개의 인덱스의 자리리를 맞바꿈
print(dataTS3.transpose(1,3).shape)

torch.Size([200, 1, 100])
torch.Size([200, 1, 1, 100])


In [20]:
## - shape 변경 => 방법 3)  transpose() : 2개의 축 원하는 축 위치로 변경
print('dataTS :', dataTS.shape)
print('dataTS2 :', dataTS2.shape)
print('dataTS3 :', dataTS3.shape)

dataTS : torch.Size([200, 100])
dataTS2 : torch.Size([200, 100, 1])
dataTS3 : torch.Size([200, 100, 1, 1])


In [21]:
print(dataTS2.permute((2,0,1)).shape)  # 전 인덱스를 지금 원하는 자리로
print(dataTS3.permute((1,0,3,2)).shape) 

torch.Size([1, 200, 100])
torch.Size([100, 200, 1, 1])


- [차원 제거] <hr>
    - 원소의 수가 바뀌면 안되기 때문에 1차원에서
    - Numpy 경우: reshape(), squeeze()
    - Pytorch 경우 : reshape(), squeeze()

In [22]:
### -----------------------------------------------------
### Numpy 경우
### -----------------------------------------------------

data2 = np.expand_dims(data, axis=2)
data3 = np.expand_dims(data2, axis=1)

print(data2.shape)
print(data3.shape)

(200, 100, 1)
(200, 1, 100, 1)


In [23]:
# 1차원 축 제거
print(data2.reshape(200, -1).shape)
print(data3.reshape(200, -1).shape)

(200, 100)
(200, 100)


In [24]:
# 1차원 축 제거 => 방법2) squeeze() : 1차원인 축들을 모두 제거
print(data2.squeeze().shape)
print(data3.squeeze().shape)
print(data3.shape)
print(data3.squeeze(axis=1).shape) # => 1번 축이 1차원이면 제거하라 ##axis지정하면 그 axis.shape이 1차원이면 제거
# 지정된 축이 1D면 삭제, 아니면 ERROR

(200, 100)
(200, 100)
(200, 1, 100, 1)
(200, 100, 1)


In [25]:
data3

array([[[[7],
         [7],
         [7],
         ...,
         [7],
         [7],
         [7]]],


       [[[7],
         [7],
         [7],
         ...,
         [7],
         [7],
         [7]]],


       [[[7],
         [7],
         [7],
         ...,
         [7],
         [7],
         [7]]],


       ...,


       [[[7],
         [7],
         [7],
         ...,
         [7],
         [7],
         [7]]],


       [[[7],
         [7],
         [7],
         ...,
         [7],
         [7],
         [7]]],


       [[[7],
         [7],
         [7],
         ...,
         [7],
         [7],
         [7]]]])

In [26]:
### -----------------------------------------------------
### Pytorch 경우
### -----------------------------------------------------

data2 = np.expand_dims(data, axis=2)
data3 = np.expand_dims(data2, axis=1)

dataTS2=torch.IntTensor(data2)
dataTS3=torch.IntTensor(data3)

print(dataTS2.shape)
print(dataTS3.shape)

torch.Size([200, 100, 1])
torch.Size([200, 1, 100, 1])


In [27]:
# 1차원 축 제거 => 방법1) reshape()
print(dataTS2.reshape(200, -1).shape)
print(dataTS3.reshape(200, -1).shape)

torch.Size([200, 100])
torch.Size([200, 100])


In [28]:
# 1차원 축 제거 => 방법2) squeeze()
print(dataTS2.squeeze().shape)
print(dataTS3.squeeze().shape)
print(dataTS3.squeeze(dim=1).shape)
print(dataTS3.squeeze(dim=0).shape) # 0이 1차원이 아니여도 ERROR가 안남. 그냥 안지우는 것뿐

torch.Size([200, 100])
torch.Size([200, 100])
torch.Size([200, 100, 1])
torch.Size([200, 1, 100, 1])


In [29]:
### Pytorch에서 메서드의 경우 메서드명_() : 원본 텐서에 적용 즉, pandas dml inplace =True 와 동일
print(dataTS3.squeeze_(dim=1).shape) # 끝에 _이거 있는 것들: PANDAS의 in_place 매개변수와 같음 : 원본에 적용시킴

torch.Size([200, 100, 1])


In [30]:
dataTS3.shape

torch.Size([200, 100, 1])

In [31]:
dataTS3.reshape(-1) # 이러면 다 1차원됨 
 

tensor([7, 7, 7,  ..., 7, 7, 7], dtype=torch.int32)